In [1]:
import pandas as pd

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/hc/3khftnwn5j75vz_4z4391z9r0000gn/T/ipykernel_9810/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/hc/3khftnwn5j75vz_4z4391z9r0000gn/T/ipykernel_9810/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/hc/3khftnwn5j75vz_4z4391z9r0000gn/T/ipykernel_9810/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 50, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 701, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 429, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/hc/3khftnwn5j75vz_4z4391z9r0000gn/T/ipykernel_9810/4080736814.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 64, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 60, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
df_OnlineAnalysis_csv = pd.read_csv('Online Results Metrics - OnlineAnalysis.csv')
df_EngagedAnalysis_csv = pd.read_csv('Results Metrics - EngagedAnalysis.csv')

In [3]:
spec_peaks = .05 # Spec for peaks - 5 cm  
speak_abs = .025 # Spec for abs - 2.5 cm   



ONLINE_RUNS_COLLECTED = 14  # Normalmente aqui el valor aqui es 15.  
                            # 5 runs x 3 samples = 15 


CURVE_RUNS_COLLECTED = 9        # 3 runs x 3 samples = 9

In [4]:
#In case columns are not in CSV just raise an error

if 'MAXABSIMPXTE (m)' not in df_OnlineAnalysis_csv.columns and df_EngagedAnalysis_csv:
    raise KeyError(f"MAXABSIMPXTE (m) column is not in csv")

if 'AVGABSIMPXTE (m)' not in df_OnlineAnalysis_csv.columns and df_EngagedAnalysis_csv:
    raise KeyError(f"AVGABSIMPXTE (m) column is not in csv")

In [5]:
# Lista con el nombre de las columnas que nos seran utiles para el analisis. 
# Estas columnas son las mismas para el analisis ONLINE que para curvas
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)'] 

# Se crea el dataframe que tendra las runs de straight swaths
# El rango va desde 0 hasta el numero de samples recolectados. El ultimo numero queda excluido. 
df_online = df_OnlineAnalysis_csv[perf_metrics].iloc[0:ONLINE_RUNS_COLLECTED] 

#Se crea el dataframe que tendra las runs de curve swaths.
# El rango va desde el numero que quedo excluido contenido en ONLINE_RUNS_COLLLECTED hasta el numero de samples colectados para las curvas
df_curves = df_EngagedAnalysis_csv[perf_metrics].iloc[ONLINE_RUNS_COLLECTED:CURVE_RUNS_COLLECTED+ONLINE_RUNS_COLLECTED].copy()
df_curves.index = range(ONLINE_RUNS_COLLECTED,CURVE_RUNS_COLLECTED+ONLINE_RUNS_COLLECTED)

In [6]:
#Verifica que solo se vean las corridas desde run 1 hasta run 5. 
print(df_online.head(ONLINE_RUNS_COLLECTED+1))

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059

In [7]:
#Verifica que solo se vean las corridas desde run 6 hasta run 8. 
print(df_curves.head(CURVE_RUNS_COLLECTED+1))

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
14  Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021
15  Run 16 - Magnum_380_run_6_5mph_2             0.062             0.017
16  Run 17 - Magnum_380_run_6_5mph_3             0.051             0.015
17  Run 18 - Magnum_380_run_7_5mph_1             0.097             0.030
18  Run 19 - Magnum_380_run_7_5mph_2             0.094             0.029
19  Run 20 - Magnum_380_run_7_5mph_3             0.092             0.027
20  Run 21 - Magnum_380_run_8_8mph_1             0.158             0.049
21  Run 22 - Magnum_380_run_8_8mph_2             0.251             0.077
22  Run 23 - Magnum_380_run_8_8mph_3             0.142             0.066

#### Specify the ranges to analyze

In [8]:
#Online runs start / stop index
run_1_start_index, run_1_stop_index = (0, 1)
run_2_start_index, run_2_stop_index = (2, 4)
run_3_start_index, run_3_stop_index = (5, 7)
run_4_start_index, run_4_stop_index = (8, 10)
run_5_start_index, run_5_stop_index = (11, 13)

#Curve runs start / stop index
run_6_start_index, run_6_stop_index = (14, 16)
run_7_start_index, run_7_stop_index = (17, 19)
run_8_start_index, run_8_stop_index = (20, 22)

In [9]:
#Aqui solo se crean SUB-DATAFRAMES 


# tomando como referencia el numero de fila de cuando empieza 
# y cuando termina cada run en DATAFRAME_ONLINE.


#for the first scenarios we use iloc 
run_1_ranges = df_online.iloc[run_1_start_index : run_1_stop_index+1]
run_2_ranges = df_online.iloc[run_2_start_index : run_2_stop_index+1]
run_3_ranges = df_online.iloc[run_3_start_index : run_3_stop_index+1]
run_4_ranges = df_online.iloc[run_4_start_index : run_4_stop_index+1]
run_5_ranges = df_online.iloc[run_5_start_index : run_5_stop_index+1]



#for the curve scenarios we use loc, since the new "index" was defined in previous steps.
# we use loc becuase that will take the index labels intead of the actual indexes


run_6_ranges = df_curves.loc[run_6_start_index : run_6_stop_index]
run_7_ranges = df_curves.loc[run_7_start_index : run_7_stop_index]
run_8_ranges = df_curves.loc[run_8_start_index : run_8_stop_index]

In [10]:
#Verifica que los rangos sean correctos

print(f"\t\t\tRUN 1 SAMPLES - ONLINE\n")
print(run_1_ranges)
print(f"\n\t\t\tRUN 2 SAMPLES - ONLINE\n")
print(run_2_ranges)
print(f"\n\t\t\tRUN 3 SAMPLES - ONLINE\n")
print(run_3_ranges)
print(f"\n\t\t\tRUN 4 SAMPLES - ONLINE\n")
print(run_4_ranges)
print(f"\n\t\t\tRUN 5 SAMPLES -ONLINE\n")
print(run_5_ranges)

			RUN 1 SAMPLES - ONLINE

                          Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0  Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1  Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017

			RUN 2 SAMPLES - ONLINE

                       Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
2  Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3  Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4  Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012

			RUN 3 SAMPLES - ONLINE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
5  Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6  Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7  Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023

			RUN 4 SAMPLES - ONLINE

                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
8    Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9   Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10  Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023

			RUN 5 SAMPLES -ONLINE

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059

In [11]:
print(f"\n\t\t\tRUN 6 SAMPLES - CURVE\n")
print(run_6_ranges)

print(f"\n\t\t\tRUN 7 SAMPLES - CURVE \n")
print(run_7_ranges)

print(f"\n\t\t\tRUN 8 SAMPLES - CURVE \n")
print(run_8_ranges)

			RUN 6 SAMPLES - CURVE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
14  Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021
15  Run 16 - Magnum_380_run_6_5mph_2             0.062             0.017
16  Run 17 - Magnum_380_run_6_5mph_3             0.051             0.015

			RUN 7 SAMPLES - CURVE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
17  Run 18 - Magnum_380_run_7_5mph_1             0.097             0.030
18  Run 19 - Magnum_380_run_7_5mph_2             0.094             0.029
19  Run 20 - Magnum_380_run_7_5mph_3             0.092             0.027

			RUN 8 SAMPLES - CURVE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
20  Run 21 - Magnum_380_run_8_8mph_1             0.158             0.049
21  Run 22 - Magnum_380_run_8_8mph_2             0.251             0.077
22  Run 23 - Magnum_380_run_8_8mph_3             0.142             0.066

In [12]:
#Se crea una minifuncion que toma como entrada el SUB-DATAFRAME de cada run (run_x_ranges).


#Entrega una tupla que contine dos valores.
#   1. El promedio de las columna MAXABSIMPXTE (m) 
#   2. El promedio de la columna  AVGABSIMPXTE (m)


def compute_mean(range_run):
    avg_peaks = range_run['MAXABSIMPXTE (m)'].mean()
    avg_abs = range_run['AVGABSIMPXTE (m)'].mean()
    return avg_peaks, avg_abs

In [13]:
#Se aplica la funcion en cada SUB-DATAFRAME por cada run 

#Online runs
avg_run_1 = compute_mean(run_1_ranges)
avg_run_2 = compute_mean(run_2_ranges)
avg_run_3 = compute_mean(run_3_ranges)
avg_run_4 = compute_mean(run_4_ranges)
avg_run_5 = compute_mean(run_5_ranges)

#Curve runs
avg_run_6 = compute_mean(run_6_ranges)
avg_run_7 = compute_mean(run_7_ranges)
avg_run_8 = compute_mean(run_8_ranges)

In [14]:
#se crea una lista con el nombre de las columnas que llevara el df de salida (output_df)

columns_names = ["PEAKS AVG (m)", "ABS AVG (m)"] 

# Se crea el df de salida. (output_df_online)
# Contendra 5 renglones con los resultados de cada run ONLINE.
output_df_online =  pd.DataFrame(index= range(5), columns=columns_names) 

# Se crea el df de salida. (output_df_curves)
# Contendra 3 renglones con los resultados de cada run CURVES.

output_df_curves =  pd.DataFrame(index= range(3), columns=columns_names)

In [15]:
# Se asigna a cada renglon del dataframe de salida (output_df) la tupla obtenida en el paso anterior 
# La tupla contiene los promedios AXABSIMPXTE (m) y AVGABSIMPXTE (m) por corrida.

output_df_online.iloc[0] = avg_run_1
output_df_online.iloc[1] = avg_run_2
output_df_online.iloc[2] = avg_run_3
output_df_online.iloc[3] = avg_run_4
output_df_online.iloc[4] = avg_run_5

In [16]:
output_df_curves.iloc[0] = avg_run_6
output_df_curves.iloc[1] = avg_run_7
output_df_curves.iloc[2] = avg_run_8

In [17]:
output_df_curves

  PEAKS AVG (m) ABS AVG (m)
0      0.064667    0.017667
1      0.094333    0.028667
2      0.183667       0.064

In [18]:
#Crea una lista de 1 a 6. El 6 no se incluye.  RangeIndex: 5 entries, 0 to 5.
# Esta columna solo tendra el numero de las corridas. 
# 
# No es necesario cambiarlo porque siempre se evaluaran 5 corridas...
# independientemenete del numero de muestras por corrida
runs_online = [f"run {i}" for i in range(1, 6)]
runs_online = pd.Series(runs_online)



#Crea una lista en donde sea FAIL si el promedio encontrado en PEAK AVG (m) 
# para esa corrida es MAYOR al spec_PEAKS = .05 m
peak_results_online = ["Fail" if peak_run > spec_peaks else "Pass" for peak_run in output_df_online["PEAKS AVG (m)"]]
peak_results_online = pd.Series(peak_results_online)



#Crea una lista en donde sea FAIL si el promedio encontrado en ABS AVG (m) 
# para esa corrida es MAYOR al spec_ABS = .025 m
abs_results_online = ["Fail" if peak_run > speak_abs else "Pass" for peak_run in output_df_online["ABS AVG (m)"]]
abs_results_online = pd.Series(abs_results_online)

In [19]:
#Crea una columna llamada 'RUN' en el df output_df y se asigna la lista 
#creada en el paso anterior. La lista contine unicamente el nombre de las corridas
# runs = [run 1, run 2, ... run5 ]
output_df_online['RUN #'] = runs_online

#Crea una columna llamada 'STATUS - PEAKS AVG' en el df output_df 
# y se le asigna la lista (peak_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_online['STATUS - PEAKS AVG'] = peak_results_online

#Crea una columna llamada 'STATUS ABS AVG' en el df output_df 
# y se le asigna la lista (abs_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_online['STATUS ABS AVG'] = abs_results_online

#Reordena las columnas en este orden en el dataframe de salida
# 'RUN','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG'
output_df_online = output_df_online[['RUN #','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG']]

In [20]:
output_df_online

   RUN # PEAKS AVG (m) STATUS - PEAKS AVG ABS AVG (m) STATUS ABS AVG
0  run 1         0.036               Pass       0.019           Pass
1  run 2      0.046667               Pass       0.015           Pass
2  run 3      0.093667               Fail    0.026667           Fail
3  run 4      0.090667               Fail        0.03           Fail
4  run 5      0.140333               Fail       0.044           Fail

In [21]:
#Crea una lista de 6 a 10. El 10 no se incluye.  RangeIndex: 3 entries, 6 to 9.
# Esta columna solo tendra el numero de las corridas. 
# 
# No es necesario cambiarlo porque siempre se evaluaran 3 corridas...
# independientemenete del numero de muestras por corrida
runs_curves = [f"run {i}" for i in range(6, 9)]
runs = pd.Series(runs_curves)



#Crea una lista en donde sea FAIL si el promedio encontrado en PEAK AVG (m) 
# para esa corrida es MAYOR al spec_PEAKS = .05 m
peak_results_curves = ["Fail" if peak_run > spec_peaks else "Pass" for peak_run in output_df_curves["PEAKS AVG (m)"]]
peak_results_curves = pd.Series(peak_results_curves)



#Crea una lista en donde sea FAIL si el promedio encontrado en ABS AVG (m) 
# para esa corrida es MAYOR al spec_ABS = .025 m
abs_results_curves = ["Fail" if peak_run > speak_abs else "Pass" for peak_run in output_df_curves["ABS AVG (m)"]]
abs_results_curves = pd.Series(abs_results_curves)

In [22]:
#Crea una columna llamada 'RUN' en el df output_df y se asigna la lista 
#creada en el paso anterior. La lista contine unicamente el nombre de las corridas
# runs = [run 1, run 2, ... run5 ]
output_df_curves['RUN #'] = runs_curves

#Crea una columna llamada 'STATUS - PEAKS AVG' en el df output_df 
# y se le asigna la lista (peak_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_curves['STATUS - PEAKS AVG'] = peak_results_curves

#Crea una columna llamada 'STATUS ABS AVG' en el df output_df 
# y se le asigna la lista (abs_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_curves['STATUS ABS AVG'] = abs_results_curves

#Reordena las columnas en este orden en el dataframe de salida
# 'RUN','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG'
output_df_curves = output_df_curves[['RUN #','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG']]

In [23]:
output_df_online

   RUN # PEAKS AVG (m) STATUS - PEAKS AVG ABS AVG (m) STATUS ABS AVG
0  run 1         0.036               Pass       0.019           Pass
1  run 2      0.046667               Pass       0.015           Pass
2  run 3      0.093667               Fail    0.026667           Fail
3  run 4      0.090667               Fail        0.03           Fail
4  run 5      0.140333               Fail       0.044           Fail

In [24]:
df_curves

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
14  Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021
15  Run 16 - Magnum_380_run_6_5mph_2             0.062             0.017
16  Run 17 - Magnum_380_run_6_5mph_3             0.051             0.015
17  Run 18 - Magnum_380_run_7_5mph_1             0.097             0.030
18  Run 19 - Magnum_380_run_7_5mph_2             0.094             0.029
19  Run 20 - Magnum_380_run_7_5mph_3             0.092             0.027
20  Run 21 - Magnum_380_run_8_8mph_1             0.158             0.049
21  Run 22 - Magnum_380_run_8_8mph_2             0.251             0.077
22  Run 23 - Magnum_380_run_8_8mph_3             0.142             0.066

In [26]:
# Se crea el archivo Summary metrics.csv. 
# Este se crea con la instruccion de with open y agregando 'a', ya que de momento no exisitira

with open('Summary Metrics.csv', 'a') as output_csv_f:
    output_csv_f.write(f'Online runs collected\n\n')



# Exportamos primero todas las muestras de cada run online. (Primera tabla)
df_online.to_csv('Summary Metrics.csv', mode='a', index=False)

# Hacemos un salto de linea
with open('Summary Metrics.csv', 'a') as output_csv_f:
    output_csv_f.write('\nSummary Online runs\n')

# Exportamos el summary de los resultados 
# (Segunda tabla) -> PASS/FAIl de los AVG PEAKS y AVG ABS para runs online. 
output_df_online.to_csv('Summary Metrics.csv', mode='a', index=False)


# Abrimos el archivo nuevamente y escribimos varios renglones en blanco.
# Luego, escribimos  Curves runs collected 
#  
 
with open('Summary Metrics.csv', 'a') as output_csv_f:
    output_csv_f.write('\n\n\n')
    output_csv_f.write(f'Curves runs collected\n\n')

# Exportamos todas las muestras por cada corrida con curvas. (Primera tabla)
df_curves.to_csv('Summary Metrics.csv', mode='a', index=False)

# Hacemos un salto de linea
with open('Summary Metrics.csv', 'a') as output_csv_f:
    output_csv_f.write('\nSummary Curve runs\n')

# Exportamos el summary de los resultados 
# (Segunda tabla) -> PASS/FAIl de los AVG PEAKS y AVG ABS para runs CURVES. 
output_df_curves.to_csv('Summary Metrics.csv', mode='a', index=False)