In [106]:
import pandas as pd
import glob
import os

In [107]:
df_OnlineAnalysis_csv = pd.read_csv('Results Metrics - EngagedAnalysis.csv')
df_EngagedAnalysis_csv = pd.read_csv('Results Metrics - EngagedAnalysis.csv')

In [108]:
spec_peaks = .05 # Spec for peaks - 5 cm  
speak_abs = .025 # Spec for abs - 2.5 cm   



ONLINE_RUNS_COLLECTED = 15  # Normalmente aqui el valor aqui es 15.  
                            # 5 runs x 3 samples = 15 


CURVE_RUNS_COLLECTED = 9        # 3 runs x 3 samples = 9

In [109]:
#In case columns are not in CSV just raise an error

if 'MAXABSIMPXTE (m)' not in df_OnlineAnalysis_csv.columns and df_EngagedAnalysis_csv:
    raise KeyError(f"MAXABSIMPXTE (m) column is not in csv")

if 'AVGABSIMPXTE (m)' not in df_OnlineAnalysis_csv.columns and df_EngagedAnalysis_csv:
    raise KeyError(f"AVGABSIMPXTE (m) column is not in csv")

In [110]:
# Lista con el nombre de las columnas que nos seran utiles para el analisis. 
# Estas columnas son las mismas para el analisis ONLINE que para curvas
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)'] 

# Se crea el dataframe que tendra las runs de straight swaths
# El rango va desde 0 hasta el numero de samples recolectados. El ultimo numero queda excluido. 
df_online = df_OnlineAnalysis_csv[perf_metrics].iloc[0:ONLINE_RUNS_COLLECTED] 
df_online.index = range(1,ONLINE_RUNS_COLLECTED+1)

#Se crea el dataframe que tendra las runs de curve swaths.
# El rango va desde el numero que quedo excluido contenido en ONLINE_RUNS_COLLLECTED hasta el numero de samples colectados para las curvas
df_curves = df_EngagedAnalysis_csv[perf_metrics].iloc[ONLINE_RUNS_COLLECTED:CURVE_RUNS_COLLECTED+ONLINE_RUNS_COLLECTED].copy()
df_curves.index = range(ONLINE_RUNS_COLLECTED+1,CURVE_RUNS_COLLECTED+ONLINE_RUNS_COLLECTED+1)

In [111]:
df_curves

                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
16    Run 16 - Magnum_380_run_6_5mph_2             0.062             0.017
17    Run 17 - Magnum_380_run_6_5mph_3             0.051             0.015
18    Run 18 - Magnum_380_run_7_5mph_1             0.097             0.030
19    Run 19 - Magnum_380_run_7_5mph_2             0.094             0.029
20    Run 20 - Magnum_380_run_7_5mph_3             0.092             0.027
21    Run 21 - Magnum_380_run_8_8mph_1             0.158             0.049
22    Run 22 - Magnum_380_run_8_8mph_2             0.251             0.077
23    Run 23 - Magnum_380_run_8_8mph_3             0.142             0.066
24  Run 24 - Magnum_380_run_9_3.6mph_1             4.743             1.095

In [112]:
#Verifica que solo se vean las corridas desde run 1 hasta run 5. 
print(df_online["Data Source"].head(ONLINE_RUNS_COLLECTED+1))

1      Run 1 - Magnum_380_run_1_1.25mph_2
2      Run 2 - Magnum_380_run_1_1.25mph_3
3         Run 3 - Magnum_380_run_2_3mph_1
4         Run 4 - Magnum_380_run_2_3mph_2
5         Run 5 - Magnum_380_run_2_3mph_3
6       Run 6 - Magnum_380_run_3_6.2mph_1
7       Run 7 - Magnum_380_run_3_6.2mph_2
8       Run 8 - Magnum_380_run_3_6.2mph_3
9       Run 9 - Magnum_380_run_4_9.2mph_1
10     Run 10 - Magnum_380_run_4_9.2mph_2
11     Run 11 - Magnum_380_run_4_9.2mph_3
12    Run 12 - Magnum_380_run_5_12.4mph_1
13    Run 13 - Magnum_380_run_5_12.4mph_2
14    Run 14 - Magnum_380_run_5_12.4mph_3
15       Run 15 - Magnum_380_run_6_5mph_1
Name: Data Source, dtype: object

In [113]:
#Online runs start / stop index
run_1_start_index, run_1_stop_index = (1, 3)
run_2_start_index, run_2_stop_index = (4, 6)
run_3_start_index, run_3_stop_index = (7, 9)
run_4_start_index, run_4_stop_index = (10, 12)
run_5_start_index, run_5_stop_index = (13, 15)

In [114]:
#Verifica que solo se vean las corridas desde run 6 hasta run 8. 
print(df_curves["Data Source"].head(CURVE_RUNS_COLLECTED+1))

16      Run 16 - Magnum_380_run_6_5mph_2
17      Run 17 - Magnum_380_run_6_5mph_3
18      Run 18 - Magnum_380_run_7_5mph_1
19      Run 19 - Magnum_380_run_7_5mph_2
20      Run 20 - Magnum_380_run_7_5mph_3
21      Run 21 - Magnum_380_run_8_8mph_1
22      Run 22 - Magnum_380_run_8_8mph_2
23      Run 23 - Magnum_380_run_8_8mph_3
24    Run 24 - Magnum_380_run_9_3.6mph_1
Name: Data Source, dtype: object

#### Specify the ranges to analyze

In [115]:
#Curve runs start / stop index
run_6_start_index, run_6_stop_index = (16, 18)
run_7_start_index, run_7_stop_index = (19, 21)
run_8_start_index, run_8_stop_index = (22, 24)

In [116]:
#Aqui solo se crean SUB-DATAFRAMES 


#Online Dataframes
run_1_ranges = df_online.loc[run_1_start_index : run_1_stop_index]
run_2_ranges = df_online.loc[run_2_start_index : run_2_stop_index]
run_3_ranges = df_online.loc[run_3_start_index : run_3_stop_index]
run_4_ranges = df_online.loc[run_4_start_index : run_4_stop_index]
run_5_ranges = df_online.loc[run_5_start_index : run_5_stop_index]

#Curve Dataframes
run_6_ranges = df_curves.loc[run_6_start_index : run_6_stop_index]
run_7_ranges = df_curves.loc[run_7_start_index : run_7_stop_index]
run_8_ranges = df_curves.loc[run_8_start_index : run_8_stop_index]

In [117]:
#Verifica que los rangos sean correctos

print(f"\t\t\tRUN 1 SAMPLES - ONLINE\n")
print(run_1_ranges)

print(f"\n\t\t\tRUN 2 SAMPLES - ONLINE\n")
print(run_2_ranges)
print(f"\n\t\t\tRUN 3 SAMPLES - ONLINE\n")
print(run_3_ranges)
print(f"\n\t\t\tRUN 4 SAMPLES - ONLINE\n")
print(run_4_ranges)
print(f"\n\t\t\tRUN 5 SAMPLES -ONLINE\n")
print(run_5_ranges)

			RUN 1 SAMPLES - ONLINE

                          Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
1  Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
2  Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
3     Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019

			RUN 2 SAMPLES - ONLINE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
4    Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
5    Run 5 - Magnum_380_run_2_3mph_3             0.051             0.014
6  Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034

			RUN 3 SAMPLES - ONLINE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
7  Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.031
8  Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.025
9  Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037

			RUN 4 SAMPLES - ONLINE

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
10   Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.031
11   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.024
12  Run 12 - Magnum_380_run_5_12.4mph_1             0.086             0.030

			RUN 5 SAMPLES -ONLINE

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
13  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.044
14  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059
15     Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021

In [118]:
print(f"\n\t\t\tRUN 6 SAMPLES - CURVE\n")
print(run_6_ranges)

print(f"\n\t\t\tRUN 7 SAMPLES - CURVE \n")
print(run_7_ranges)

print(f"\n\t\t\tRUN 8 SAMPLES - CURVE \n")
print(run_8_ranges)

			RUN 6 SAMPLES - CURVE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
16  Run 16 - Magnum_380_run_6_5mph_2             0.062             0.017
17  Run 17 - Magnum_380_run_6_5mph_3             0.051             0.015
18  Run 18 - Magnum_380_run_7_5mph_1             0.097             0.030

			RUN 7 SAMPLES - CURVE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
19  Run 19 - Magnum_380_run_7_5mph_2             0.094             0.029
20  Run 20 - Magnum_380_run_7_5mph_3             0.092             0.027
21  Run 21 - Magnum_380_run_8_8mph_1             0.158             0.049

			RUN 8 SAMPLES - CURVE

                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
22    Run 22 - Magnum_380_run_8_8mph_2             0.251             0.077
23    Run 23 - Magnum_380_run_8_8mph_3             0.142             0.066
24  Run 24 - Magnum_380_run_9_3.6mph_1             4.743             1.095

In [119]:
#Se crea una minifuncion que toma como entrada el SUB-DATAFRAME de cada run (run_x_ranges).


#Entrega una tupla que contine dos valores.
#   1. El promedio de las columna MAXABSIMPXTE (m) 
#   2. El promedio de la columna  AVGABSIMPXTE (m)


def compute_mean(range_run):
    avg_peaks = range_run['MAXABSIMPXTE (m)'].mean()
    avg_abs = range_run['AVGABSIMPXTE (m)'].mean()
    return avg_peaks, avg_abs

In [120]:
#Se aplica la funcion en cada SUB-DATAFRAME por cada run 

#Online runs
avg_run_1 = compute_mean(run_1_ranges)
avg_run_2 = compute_mean(run_2_ranges)
avg_run_3 = compute_mean(run_3_ranges)
avg_run_4 = compute_mean(run_4_ranges)
avg_run_5 = compute_mean(run_5_ranges)

#Curve runs
avg_run_6 = compute_mean(run_6_ranges)
avg_run_7 = compute_mean(run_7_ranges)
avg_run_8 = compute_mean(run_8_ranges)

In [121]:
#se crea una lista con el nombre de las columnas que llevara el df de salida (output_df)

columns_names = ["PEAKS AVG (m)", "ABS AVG (m)"] 

# Se crea el df de salida. (output_df_online)
# Contendra 5 renglones con los resultados de cada run ONLINE.
output_df_online =  pd.DataFrame(index= range(5), columns=columns_names) 

# Se crea el df de salida. (output_df_curves)
# Contendra 3 renglones con los resultados de cada run CURVES.

output_df_curves =  pd.DataFrame(index= range(3), columns=columns_names)

In [122]:
# Se asigna a cada renglon del dataframe de salida (output_df) la tupla obtenida en el paso anterior 
# La tupla contiene los promedios AXABSIMPXTE (m) y AVGABSIMPXTE (m) por corrida.

output_df_online.iloc[0] = avg_run_1
output_df_online.iloc[1] = avg_run_2
output_df_online.iloc[2] = avg_run_3
output_df_online.iloc[3] = avg_run_4
output_df_online.iloc[4] = avg_run_5

In [123]:
output_df_curves.iloc[0] = avg_run_6
output_df_curves.iloc[1] = avg_run_7
output_df_curves.iloc[2] = avg_run_8

In [124]:
#Crea una lista de 1 a 6. El 6 no se incluye.  RangeIndex: 5 entries, 0 to 5.
# Esta columna solo tendra el numero de las corridas. 
# 
# No es necesario cambiarlo porque siempre se evaluaran 5 corridas...
# independientemenete del numero de muestras por corrida
runs_online = [f"run {i}" for i in range(1, 6)]
runs_online = pd.Series(runs_online)



#Crea una lista en donde sea FAIL si el promedio encontrado en PEAK AVG (m) 
# para esa corrida es MAYOR al spec_PEAKS = .05 m
peak_results_online = ["Fail" if peak_run > spec_peaks else "Pass" for peak_run in output_df_online["PEAKS AVG (m)"]]
peak_results_online = pd.Series(peak_results_online)



#Crea una lista en donde sea FAIL si el promedio encontrado en ABS AVG (m) 
# para esa corrida es MAYOR al spec_ABS = .025 m
abs_results_online = ["Fail" if peak_run > speak_abs else "Pass" for peak_run in output_df_online["ABS AVG (m)"]]
abs_results_online = pd.Series(abs_results_online)

In [125]:
#Crea una columna llamada 'RUN' en el df output_df y se asigna la lista 
#creada en el paso anterior. La lista contine unicamente el nombre de las corridas
# runs = [run 1, run 2, ... run5 ]
output_df_online['RUN #'] = runs_online

#Crea una columna llamada 'STATUS - PEAKS AVG' en el df output_df 
# y se le asigna la lista (peak_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_online['STATUS - PEAKS AVG'] = peak_results_online

#Crea una columna llamada 'STATUS ABS AVG' en el df output_df 
# y se le asigna la lista (abs_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_online['STATUS ABS AVG'] = abs_results_online

#Reordena las columnas en este orden en el dataframe de salida
# 'RUN','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG'
output_df_online = output_df_online[['RUN #','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG']]

In [126]:
output_df_online

   RUN # PEAKS AVG (m) STATUS - PEAKS AVG ABS AVG (m) STATUS ABS AVG
0  run 1      0.040333               Pass       0.019           Pass
1  run 2      0.073333               Fail    0.020667           Pass
2  run 3      0.087333               Fail       0.031           Fail
3  run 4         0.083               Fail    0.028333           Fail
4  run 5         0.139               Fail    0.041333           Fail

In [127]:
#Crea una lista de 6 a 10. El 10 no se incluye.  RangeIndex: 3 entries, 6 to 9.
# Esta columna solo tendra el numero de las corridas. 
# 
# No es necesario cambiarlo porque siempre se evaluaran 3 corridas...
# independientemenete del numero de muestras por corrida
runs_curves = [f"run {i}" for i in range(6, 9)]
runs = pd.Series(runs_curves)



#Crea una lista en donde sea FAIL si el promedio encontrado en PEAK AVG (m) 
# para esa corrida es MAYOR al spec_PEAKS = .05 m
peak_results_curves = ["Fail" if peak_run > spec_peaks else "Pass" for peak_run in output_df_curves["PEAKS AVG (m)"]]
peak_results_curves = pd.Series(peak_results_curves)



#Crea una lista en donde sea FAIL si el promedio encontrado en ABS AVG (m) 
# para esa corrida es MAYOR al spec_ABS = .025 m
abs_results_curves = ["Fail" if peak_run > speak_abs else "Pass" for peak_run in output_df_curves["ABS AVG (m)"]]
abs_results_curves = pd.Series(abs_results_curves)

In [128]:
#Crea una columna llamada 'RUN' en el df output_df y se asigna la lista 
#creada en el paso anterior. La lista contine unicamente el nombre de las corridas
# runs = [run 1, run 2, ... run5 ]
output_df_curves['RUN #'] = runs_curves

#Crea una columna llamada 'STATUS - PEAKS AVG' en el df output_df 
# y se le asigna la lista (peak_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_curves['STATUS - PEAKS AVG'] = peak_results_curves

#Crea una columna llamada 'STATUS ABS AVG' en el df output_df 
# y se le asigna la lista (abs_results) que contiene los resultados obtenidos (Pass o Fail).
output_df_curves['STATUS ABS AVG'] = abs_results_curves

#Reordena las columnas en este orden en el dataframe de salida
# 'RUN','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG'
output_df_curves = output_df_curves[['RUN #','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG']]

In [129]:

# Exportamos primero todas las muestras de cada run online. (Primera tabla)
df_online.to_csv('Online Runs.csv', index=False)


# Exportamos el summary de los resultados 
# (Segunda tabla) -> PASS/FAIl de los AVG PEAKS y AVG ABS para runs online. 
output_df_online.to_csv('Summary Online Results.csv', index=False)


# Exportamos todas las muestras por cada corrida con curvas. (Primera tabla)
df_curves.to_csv('Curve Runs.csv', index=False)


# Exportamos el summary de los resultados 
# (Segunda tabla) -> PASS/FAIl de los AVG PEAKS y AVG ABS para runs CURVES. 
output_df_curves.to_csv('Summary Curve Results.csv', index=False)

In [ ]:
csv_files = glob.glob('*.csv')
summary_excel_report = 'Test Status Report - Online and Curves PIG perfomance.xlsx'


with pd.ExcelWriter(summary_excel_report, engine='openpyxl') as writer:
    for file in csv_files:
        # Extract the file name without the .csv extension for the sheet name
        sheet_name = os.path.splitext(os.path.basename(file))[0]
        
        # Excel sheet names have a strict 31-character limit
        sheet_name = sheet_name[:31]
        
        # Read the CSV and write it to its own Excel tab
        df = pd.read_csv(file)
        df.to_excel(writer, sheet_name=sheet_name, index=False)