In [50]:
import pandas as pd

In [51]:
df = pd.read_csv('OnlineAnalysis.csv')

In [52]:
#In case columns are not in CSV just raise an error

if 'MAXABSIMPXTE (m)' not in df.columns:
    raise KeyError(f"MAXABSIMPXTE (m) column is not in csv")

if 'AVGABSIMPXTE (m)' not in df.columns:
    raise KeyError(f"AVGABSIMPXTE (m) column is not in csv")

In [53]:
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)']
df_online = df[perf_metrics].iloc[0:15] #Aqui solo se necesitan los primeros 15 renglones
df_online.head(20)

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059
14     Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021

In [54]:
columns = ["PEAKS AVG (m)", "ABS AVG (m)"] #se crean las colmnas del df de salida
output_df =  pd.DataFrame(index= range(5), columns=columns)

In [55]:
df_online.head(20)

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059
14     Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021

## User interaction: 
#### Specify the ranges to analyze

In [56]:
run_1_start_index = 0
run_1_stop_index = 1

run_2_start_index = 2
run_2_stop_index = 4

run_3_start_index = 5
run_3_stop_index = 7

run_4_start_index = 8
run_4_stop_index = 10

run_5_start_index = 11
run_5_stop_index = 13

In [57]:
run_1_ranges = df_online.iloc[run_1_start_index : run_1_stop_index+1]
run_2_ranges = df_online.iloc[run_2_start_index : run_2_stop_index+1]
run_3_ranges = df_online.iloc[run_3_start_index : run_3_stop_index+1]
run_4_ranges = df_online.iloc[run_4_start_index : run_4_stop_index+1]
run_5_ranges = df_online.iloc[run_5_start_index : run_5_stop_index+1]

In [58]:
print(f"\t\t\tRUN 1 RANGE\n")
print(run_1_ranges)
print(f"\n\t\t\tRUN 2 RANGE\n")
print(run_2_ranges)
print(f"\n\t\t\tRUN 3 RANGE\n")
print(run_3_ranges)
print(f"\n\t\t\tRUN 4 RANGE\n")
print(run_4_ranges)
print(f"\n\t\t\tRUN 5 RANGE\n")
print(run_5_ranges)

			RUN 1 RANGE

                          Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0  Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1  Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017

			RUN 2 RANGE

                       Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
2  Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3  Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4  Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012

			RUN 3 RANGE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
5  Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6  Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7  Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023

			RUN 4 RANGE

                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
8    Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9   Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10  Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023

			RUN 5 RANGE

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059

In [59]:
def compute_mean(range_run):
    avg_peaks = range_run['MAXABSIMPXTE (m)'].mean()
    avg_abs = range_run['AVGABSIMPXTE (m)'].mean()
    return avg_peaks, avg_abs

In [60]:
avg_run_1 = compute_mean(run_1_ranges)
avg_run_2 = compute_mean(run_2_ranges)
avg_run_3 = compute_mean(run_3_ranges)
avg_run_4 = compute_mean(run_4_ranges)
avg_run_5 = compute_mean(run_5_ranges)

In [61]:
output_df.iloc[0] = avg_run_1
output_df.iloc[1] = avg_run_2
output_df.iloc[2] = avg_run_3
output_df.iloc[3] = avg_run_4
output_df.iloc[4] = avg_run_5

In [62]:
output_df

  PEAKS AVG (m) ABS AVG (m)
0         0.036       0.019
1      0.046667       0.015
2      0.093667    0.026667
3      0.090667        0.03
4      0.140333       0.044

In [63]:
output_df['PEAKS OVER 5 cm'] = output_df["PEAKS AVG (m)"]>.05
output_df['ABS OVER 2.5 cm'] = output_df["ABS AVG (m)"]>.025
output_df

  PEAKS AVG (m) ABS AVG (m)  PEAKS OVER 5 cm  ABS OVER 2.5 cm
0         0.036       0.019            False            False
1      0.046667       0.015            False            False
2      0.093667    0.026667             True             True
3      0.090667        0.03             True             True
4      0.140333       0.044             True             True

In [ ]:
df_online.iloc[0:13].to_csv('output.csv', index=False)

with open('output.csv', 'a') as output_csv_f:
    output_csv_f.write('\n')

output_df.to_csv('output.csv', mode='a', index=False)