In [47]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font

In [48]:
bundle_version = 'sum_v3 tesing report'

Definir los archivos CSV que se usaran para los escenarios online y curve

Para online: SettleAnalysis


Para curve: EngageAnalysis

In [49]:
#vehicle settle para Online runs 

#Engaged Analysis para Curve runs

online_csv_path = 'Vehicle Settled Results Metrics - VehicleSettledAnalysis.csv'
curve_csv_path  = 'Results Metrics - EngagedAnalysis.csv'

In [50]:
# Se especifica aqui, Software version y el nombre del archivo excel que se exportara

filename_excel_report = bundle_version + '_Test Status Report.xlsx' 


#Se leen los archivos que tienen la informacion para el analisis 


df_OnlineAnalysis_csv = pd.read_csv(online_csv_path)  
df_EngagedAnalysis_csv = pd.read_csv(curve_csv_path)



#Specs for peaks and absolutes
spec_peaks = .05 # Spec for peaks - 5 cm  
speak_abs = .025 # Spec for abs - 2.5 cm  



# Lista con el nombre de las columnas que nos seran utiles para el analisis. 
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)']

A continuacion se despliega el dataframe online. 

- Poner atencion en:
    - row idx de  straight_1.25mph_run1 
    

    
    - row idx de  straight_12.4mph_run3

In [51]:
df_OnlineAnalysis_csv.columns

Index(['Kringle Event UUID', 'Kringle Event Start Datetime (UTC)',
       'AVGVelocity (mps)', 'Data Source', 'IMPSettlingDistance (m)',
       'IMPSettlingTime (s)', 'AVGABSCommandAngle (deg)', 'AVGABSIMPXTE (m)',
       'AVGABSRoll (deg)', 'AVGABSSteeringAngle (deg)', 'AVGABSXTE (m)',
       'AVGCommandAngle (deg)', 'AVGIMPXTE (m)', 'AVGRoll (deg)',
       'AVGSpeed (mps)', 'AVGSteeringAngle (deg)', 'AVGXTE (m)',
       'Distance (m)', 'Duration (s)', 'MAXABSCommandAngle (deg)',
       'MAXABSCommandSlew (dps)', 'MAXABSIMPXTE (m)', 'MAXABSRoll (deg)',
       'MAXABSSteeringAngle (deg)', 'MAXABSSteeringSlew (dps)',
       'MAXABSXTE (m)', 'MAXIMPXTE (m)', 'MAXXTE (m)', 'MINABSIMPXTE (m)',
       'MINABSRoll (deg)', 'MINABSXTE (m)', 'MINIMPXTE (m)', 'MINXTE (m)',
       'STDCommandAngle (deg)', 'STDIMPXTE (m)', 'STDRoll (deg)',
       'STDSteeringAngle (deg)', 'STDXTE (m)', 'SteeringDelay (deg)',
       'SwathType (None)'],
      dtype='str')

In [52]:
df_OnlineAnalysis_csv["Data Source"]

0            Run 1 - Magnum_380_straight_1.25mph_run1
1            Run 2 - Magnum_380_straight_1.25mph_run2
2            Run 3 - Magnum_380_straight_1.25mph_run3
3             Run 4 - Magnum_380_straight_3.1mph_run1
4             Run 5 - Magnum_380_straight_3.1mph_run2
5             Run 6 - Magnum_380_straight_3.1mph_run2
6             Run 7 - Magnum_380_straight_3.1mph_run3
7             Run 8 - Magnum_380_straight_3.1mph_run3
8             Run 9 - Magnum_380_straight_6.2mph_run1
9            Run 10 - Magnum_380_straight_6.2mph_run1
10           Run 11 - Magnum_380_straight_6.2mph_run2
11           Run 12 - Magnum_380_straight_6.2mph_run3
12           Run 13 - Magnum_380_straight_9.2mph_run1
13           Run 14 - Magnum_380_straight_9.2mph_run1
14           Run 15 - Magnum_380_straight_9.2mph_run2
15           Run 16 - Magnum_380_straight_9.2mph_run2
16           Run 17 - Magnum_380_straight_9.2mph_run2
17           Run 18 - Magnum_380_straight_9.2mph_run2
18           Run 19 - Magnum_380_straight_9.2mph_run3
19          Run 20 - Magnum_380_straight_12.4mph_run1
20          Run 21 - Magnum_380_straight_12.4mph_run1
21          Run 22 - Magnum_380_straight_12.4mph_run2
22          Run 23 - Magnum_380_straight_12.4mph_run3
23            Run 24 - Magnum_380_curve1deg_5mph_run1
24            Run 25 - Magnum_380_curve1deg_5mph_run1
25            Run 26 - Magnum_380_curve2deg_5mph_run2
26       Run 27 - Magnum_380_aqc_parallel_3.6mph_run1
27         Run 28 - Magnum_380_aqc_parallel_5mph_run1
28         Run 29 - Magnum_380_aqc_parallel_5mph_run1
29         Run 30 - Magnum_380_aqc_parallel_8mph_run1
30    Run 31 - Magnum_380_aqc_30deg_10ft__3.6mph_run1
31    Run 32 - Magnum_380_aqc_30deg_10ft__3.6mph_run1
32    Run 33 - Magnum_380_aqc_30deg_25ft__3.6mph_run1
33      Run 34 - Magnum_380_aqc_30deg_10ft__5mph_run1
34      Run 35 - Magnum_380_aqc_30deg_25ft__5mph_run1
35      Run 36 - Magnum_380_aqc_30deg_10ft__8mph_run1
36      Run 37 - Magnum_380_aqc_30deg_25ft__8mph_run1
37    Run 38 - Magnum_380_aqc_75deg_10ft__3.6mph_run1
38    Run 39 - Magnum_380_aqc_75deg_30ft__3.6mph_run1
39      Run 40 - Magnum_380_aqc_75deg_10ft__5mph_run1
40      Run 41 - Magnum_380_aqc_75deg_30ft__5mph_run1
41    Run 42 - Magnum_380_aqc_75deg_10ft__3.6mph_run2
42      Run 43 - Magnum_380_aqc_75deg_30ft__5mph_run2
Name: Data Source, dtype: str

Escribe el row idx de straight_1.25mph_run1 en la variable start_row_idx_online


Escribe el row idx de straight_12.4mph_run3 en la variable end_row_idx_online

In [53]:
start_row_idx_online = 0 # Poner el row index de straight_1.25mph_run1
end_row_idx_online = 22 # Poner el row index de straight_12.4mph_run3

In [89]:
df_online = df_OnlineAnalysis_csv[perf_metrics].iloc[0 : end_row_idx_online + 1]
df_online.index = range(1,len(df_online) + 1)
df_online.rename(columns={'Data Source': 'Run Description'},inplace=True)

Verifica que en df_online solo tenga las runs de straight

In [90]:
print(df_online)

                              Run Description  MAXABSIMPXTE (m)  \
1    Run 1 - Magnum_380_straight_1.25mph_run1             0.047
2    Run 2 - Magnum_380_straight_1.25mph_run2             0.028
3    Run 3 - Magnum_380_straight_1.25mph_run3             0.031
4     Run 4 - Magnum_380_straight_3.1mph_run1             0.038
5     Run 5 - Magnum_380_straight_3.1mph_run2             0.027
6     Run 6 - Magnum_380_straight_3.1mph_run2             0.064
7     Run 7 - Magnum_380_straight_3.1mph_run3             0.054
8     Run 8 - Magnum_380_straight_3.1mph_run3             0.040
9     Run 9 - Magnum_380_straight_6.2mph_run1             0.065
10   Run 10 - Magnum_380_straight_6.2mph_run1             0.049
11   Run 11 - Magnum_380_straight_6.2mph_run2             0.060
12   Run 12 - Magnum_380_straight_6.2mph_run3             0.053
13   Run 13 - Magnum_380_straight_9.2mph_run1             0.050
14   Run 14 - Magnum_380_straight_9.2mph_run1             0.121
15   Run 15 - Magnum_380_straight_9.2mph_run2             0.078
16   Run 16 - Magnum_380_straight_9.2mph_run2             0.062
17   Run 17 - Magnum_380_straight_9.2mph_run2             0.077
18   Run 18 - Magnum_380_straight_9.2mph_run2             0.079
19   Run 19 - Magnum_380_straight_9.2mph_run3             0.064
20  Run 20 - Magnum_380_straight_12.4mph_run1             0.087
21  Run 21 - Magnum_380_straight_12.4mph_run1             0.061
22  Run 22 - Magnum_380_straight_12.4mph_run2             0.044
23  Run 23 - Magnum_380_straight_12.4mph_run3             0.060

    AVGABSIMPXTE (m)
1              0.028
2              0.015
3              0.009
4              0.010
5              0.016
6              0.019
7              0.018
8              0.014
9              0.024
10             0.017
11             0.019
12             0.014
13             0.018
14             0.023
15             0.024
16             0.034
17             0.031
18             0.028
19             0.026
20             0.029
21             0.030
22             0.016
23             0.018

Se realiza el mismo proceso para el dataframe que contiene las runs de curve. 

- Poner atencion en:
    - row idx de  curve1deg_5mph
    

    
    - row idx de  curve1deg_8mph

In [56]:
df_EngagedAnalysis_csv["Data Source"]

0            Run 1 - Magnum_380_straight_1.25mph_run1
1            Run 2 - Magnum_380_straight_1.25mph_run2
2            Run 3 - Magnum_380_straight_1.25mph_run3
3             Run 4 - Magnum_380_straight_3.1mph_run1
4             Run 5 - Magnum_380_straight_3.1mph_run2
5             Run 6 - Magnum_380_straight_3.1mph_run3
6             Run 7 - Magnum_380_straight_6.2mph_run1
7             Run 8 - Magnum_380_straight_6.2mph_run2
8             Run 9 - Magnum_380_straight_6.2mph_run3
9            Run 10 - Magnum_380_straight_9.2mph_run1
10           Run 11 - Magnum_380_straight_9.2mph_run2
11           Run 12 - Magnum_380_straight_9.2mph_run3
12          Run 13 - Magnum_380_straight_12.4mph_run1
13          Run 14 - Magnum_380_straight_12.4mph_run2
14          Run 15 - Magnum_380_straight_12.4mph_run3
15            Run 16 - Magnum_380_curve1deg_5mph_run1
16            Run 17 - Magnum_380_curve1deg_5mph_run2
17            Run 18 - Magnum_380_curve1deg_5mph_run3
18            Run 19 - Magnum_380_curve2deg_5mph_run1
19            Run 20 - Magnum_380_curve2deg_5mph_run2
20            Run 21 - Magnum_380_curve2deg_5mph_run3
21            Run 22 - Magnum_380_curve1deg_8mph_run1
22            Run 23 - Magnum_380_curve1deg_8mph_run2
23            Run 24 - Magnum_380_curve1deg_8mph_run3
24       Run 25 - Magnum_380_aqc_parallel_3.6mph_run1
25         Run 26 - Magnum_380_aqc_parallel_5mph_run1
26         Run 27 - Magnum_380_aqc_parallel_8mph_run1
27    Run 28 - Magnum_380_aqc_30deg_10ft__3.6mph_run1
28    Run 29 - Magnum_380_aqc_30deg_25ft__3.6mph_run1
29      Run 30 - Magnum_380_aqc_30deg_10ft__5mph_run1
30      Run 31 - Magnum_380_aqc_30deg_25ft__5mph_run1
31      Run 32 - Magnum_380_aqc_30deg_10ft__8mph_run1
32      Run 33 - Magnum_380_aqc_30deg_25ft__8mph_run1
33    Run 34 - Magnum_380_aqc_75deg_10ft__3.6mph_run1
34    Run 35 - Magnum_380_aqc_75deg_30ft__3.6mph_run1
35      Run 36 - Magnum_380_aqc_75deg_10ft__5mph_run1
36      Run 37 - Magnum_380_aqc_75deg_30ft__5mph_run1
37    Run 38 - Magnum_380_aqc_75deg_10ft__3.6mph_run2
38      Run 39 - Magnum_380_aqc_75deg_30ft__5mph_run2
Name: Data Source, dtype: str

In [57]:
start_row_idx_curve = 15 # Poner el row index de curve1deg_5mph
end_row_idx_curve = 23 # Poner el row index de curve1deg_8mph

In [85]:
# Se crea el dataframe para las runs de curve

df_curve = df_EngagedAnalysis_csv[perf_metrics].iloc[start_row_idx_curve : end_row_idx_curve + 1]
df_curve.index = range(1,len(df_curve) + 1)
df_curve.rename(columns={'Data Source': 'Run Description'},inplace=True)

Verifica que solo se vean las corridas curve en el df_curve

In [86]:
print(df_curve)

                           Run Description  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
1  Run 16 - Magnum_380_curve1deg_5mph_run1             0.071             0.020
2  Run 17 - Magnum_380_curve1deg_5mph_run2             0.061             0.019
3  Run 18 - Magnum_380_curve1deg_5mph_run3             0.056             0.019
4  Run 19 - Magnum_380_curve2deg_5mph_run1             0.094             0.027
5  Run 20 - Magnum_380_curve2deg_5mph_run2             0.109             0.022
6  Run 21 - Magnum_380_curve2deg_5mph_run3             0.110             0.023
7  Run 22 - Magnum_380_curve1deg_8mph_run1             0.165             0.072
8  Run 23 - Magnum_380_curve1deg_8mph_run2             0.153             0.062
9  Run 24 - Magnum_380_curve1deg_8mph_run3             0.152             0.067

Se crean los dataframes

df_speeds_online : Contiene las velocidades de cada corrida

df_peaks_avg_online : Contiene el average MAX de las corridas online

df_abs_avg_online: Contiene el average de XTE de las corridas online

In [72]:
# Se crea el df que contendra los promedios de las corridas ONLINE unicamente para peaks o MAXABS

df_speeds_online = pd.DataFrame(index= range(0,5), columns= ["Speed (mph)"]) 
df_peaks_avg_online =  pd.DataFrame(index= range(0,5), columns= ["Average MAX XTE of runs"]) 
df_abs_avg_online =  pd.DataFrame(index= range(0,5), columns= ["Average XTE of runs"])

In [91]:
scenarios = ["1.25", "3.1", "6.2", "9.2", "12.4"]

avg_max = {
    s: round(
        df_online.loc[
            df_online["Run Description"].str.contains(s, na=False),
            "MAXABSIMPXTE (m)"
        ].mean(),
        2
    )
    for s in scenarios
}
avg_max = list(avg_max.values())

avg_abs = {
    a: round(
        df_online.loc[
            df_online["Run Description"].str.contains(a, na=False),
            "AVGABSIMPXTE (m)"
        ].mean(),
        2
    )
    for a in scenarios
}


avg_abs_results = list(avg_abs.values())

In [78]:
for i,avg_peak, avg_abs in zip(range(5), avg_max, avg_abs_results):
    df_speeds_online.loc[i,'Speed (mph)'] = scenarios[i]
    df_peaks_avg_online.loc[i,'Average MAX XTE of runs'] = avg_max[i]
    df_abs_avg_online.loc[i, 'Average XTE of runs'] = avg_abs_results[i]

In [79]:
df_output_online = pd.concat([df_speeds_online,
                                df_peaks_avg_online,
                                df_abs_avg_online], axis=1)

In [81]:
df_output_online

  Speed (mph) Average MAX XTE of runs Average XTE of runs
0        1.25                    0.04                0.02
1         3.1                    0.04                0.02
2         6.2                    0.06                0.02
3         9.2                    0.08                0.03
4        12.4                    0.06                0.02

Realizamos ahora la tabla para los scenarios de curvas

df_speeds_curves = pd.DataFrame(index= range(0,3), columns= ["Speed (mph)"]) 

df_curvature = pd.DataFrame(index= range(0,3), columns= ["Curvature "]) 

df_peaks_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average MAX XTE of runs"]) 

df_abs_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average XTE of runs"])

In [100]:
# Se crea el df que contendra los promedios de las corridas ONLINE unicamente para peaks o MAXABS

df_speeds_curves = pd.DataFrame(index= range(0,3), columns= ["Speed (mph)"]) 
df_curvature = pd.DataFrame(index= range(0,3), columns= ["Curvature (deg/m)"]) 
df_peaks_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average MAX XTE of runs"]) 
df_abs_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average XTE of runs"])

In [110]:
df_curve

                           Run Description  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
1  Run 16 - Magnum_380_curve1deg_5mph_run1             0.071             0.020
2  Run 17 - Magnum_380_curve1deg_5mph_run2             0.061             0.019
3  Run 18 - Magnum_380_curve1deg_5mph_run3             0.056             0.019
4  Run 19 - Magnum_380_curve2deg_5mph_run1             0.094             0.027
5  Run 20 - Magnum_380_curve2deg_5mph_run2             0.109             0.022
6  Run 21 - Magnum_380_curve2deg_5mph_run3             0.110             0.023
7  Run 22 - Magnum_380_curve1deg_8mph_run1             0.165             0.072
8  Run 23 - Magnum_380_curve1deg_8mph_run2             0.153             0.062
9  Run 24 - Magnum_380_curve1deg_8mph_run3             0.152             0.067

In [124]:
scenarios = ["curve1deg_5mph", "curve2deg", "curve1deg_8mph"]
speeds_curves = ["5", "5", "8"]
curvatures = ["1", "2", "1"]

avg_max = {
    s: round(
        df_curve.loc[
            df_curve["Run Description"].str.contains(s, na=False),
            "MAXABSIMPXTE (m)"
        ].mean(),
        2
    )
    for s in scenarios
}
avg_max = list(avg_max.values())

avg_abs = {
    a: round(
        df_curve.loc[
            df_curve["Run Description"].str.contains(a, na=False),
            "AVGABSIMPXTE (m)"
        ].mean(),
        2
    )
    for a in scenarios
}


avg_abs_results = list(avg_abs.values())

In [126]:
for i,avg_peak, avg_abs in zip(range(5), avg_max, avg_abs_results):
    df_speeds_curves.loc[i,'Speed (mph)'] = speeds_curves[i]
    df_curvature.loc[i,'Curvature (deg/m)'] = curvatures[i]
    df_peaks_avg_curve.loc[i,'Average MAX XTE of runs'] = avg_max[i]
    df_abs_avg_curve.loc[i, 'Average XTE of runs'] = avg_abs_results[i]

In [129]:
df_output_curve = pd.concat([df_speeds_curves,
                             df_curvature,
                                df_peaks_avg_curve,
                                df_abs_avg_curve], axis=1)

In [130]:
df_output_curve

  Speed (mph) Curvature (deg/m) Average MAX XTE of runs Average XTE of runs
0           5                 1                    0.06                0.02
1           5                 2                     0.1                0.02
2           8                 1                    0.16                0.07

In [ ]:
# Se exportan los dataframes al mismo excel file. 
# Sheet name nos sirve para especificar el nombre que llevara la sheet donde se exportara el df

with pd.ExcelWriter(filename_excel_report) as writer:
    df_online.to_excel(writer, sheet_name= 'Online Runs',index=False)
    df_curves.to_excel(writer, sheet_name= 'Curve Runs',index=False)
    output_df_results.to_excel(writer,sheet_name= 'Summary Results',index=False)

In [ ]:
#Se abre el archivo usando openpyxl

#Aqui solo se crea la instancia para manipular el excel usando la libreria openpyxl
wb_file = load_workbook(filename_excel_report) 

#Seleccionamos la hoja que contine los resultados 
wb_sheet = wb_file['Summary Results']

#Se crean los colores para cada celda
green_code = "C6EFCE"
red_code = "FFC7CE"


# start color: Excel pinta la celda usando cierto patron, ya sea puntos o lineas,
# start color es en palabras resumidas el color de esos puntos con los que se llena la celda

green_fill = PatternFill(start_color = green_code,
                         fill_type= 'solid')


red_fill = PatternFill(start_color = red_code,
                       fill_type = 'solid' )

 # Aqui se tomaran las columnas C (3) y la E (5) que tiene los resultados de Pass/Fail

status_columns = [3,5]


# Comenzamos desde el row 2, ya que no necesitamos leer el heading the la columna 
# contamos los siguientes 8 rows que contien los Pass o Fail por columna 
# cuando row es igual a 10, sale del bucle
for row in range(2,10):

    for col in status_columns:
        
        cell = wb_sheet.cell(row = row, column = col)

        if cell.value == "Pass":
            cell.fill = green_fill

        else:
            cell.fill = red_fill

wb_file.save(filename_excel_report)