In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('OnlineAnalysis.csv')
#print(df.head())
print(df.columns)

Index(['Kringle Event UUID', 'Kringle Event Start Datetime (UTC)',
       'AVGVelocity (mps)', 'Data Source', 'IMPSettlingDistance (m)',
       'IMPSettlingTime (s)', 'AVGABSCommandAngle (deg)', 'AVGABSIMPXTE (m)',
       'AVGABSRoll (deg)', 'AVGABSSteeringAngle (deg)', 'AVGABSXTE (m)',
       'AVGCommandAngle (deg)', 'AVGIMPXTE (m)', 'AVGRoll (deg)',
       'AVGSpeed (mps)', 'AVGSpeedkph (kph)', 'AVGSteeringAngle (deg)',
       'AVGVelocitykph (kph)', 'AVGXTE (m)', 'Distance (m)', 'Duration (s)',
       'MAXABSCommandAngle (deg)', 'MAXABSCommandSlew (dps)',
       'MAXABSIMPXTE (m)', 'MAXABSIMPXTE (cm)', 'MAXABSRoll (deg)',
       'MAXABSSteeringAngle (deg)', 'MAXABSSteeringSlew (dps)',
       'MAXABSXTE (m)', 'MAXIMPXTE (m)', 'MAXXTE (m)', 'MINABSIMPXTE (m)',
       'MINABSRoll (deg)', 'MINABSXTE (m)', 'MINIMPXTE (m)', 'MINXTE (m)',
       'STDCommandAngle (deg)', 'STDIMPXTE (m)', 'STDRoll (deg)',
       'STDSteeringAngle (deg)', 'STDXTE (m)', 'SteeringDelay (deg)',
       'SwathType (None)'],
      dtype='object')

In [9]:
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)']
df_online = df[perf_metrics].iloc[0:15] #Aqui solo se necesitan los primeros 15 renglones
df_online.head(20)

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059
14     Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021

In [10]:
columns = ["PEAKS AVG", "ABS AVG"] #se crean las colmnas del df de salida
output_df =  pd.DataFrame(index= range(5), columns=columns)

In [11]:
def get_ranges(df,start_index,samples):
    #ejemplo 
    # start index = 2
    # samples = 3
    end_index = start_index + samples   # El rango es 2 hasta 4. El 5 no se incluye
                                                #cuando llega a 5 sale de la funcion. Es como less or equal to 5

    print(f"Rows from: {start_index} to {end_index - 1}") # Se pone el -1 solo para imprimir el rango correcto

    print(df.iloc[start_index:end_index])
    peaks_range =  df['MAXABSIMPXTE (m)'].iloc[start_index:end_index] #Del df toma la col MAXABSIMPXTE y ... 
                                                                    # los renglones 2 hasta 4. Cuando llega a 5 break.


    abs_range =  df['AVGABSIMPXTE (m)'].iloc[start_index:end_index] #Del df toma la col AVGABSIMPXTE y ... 
    
                                                                    # los renglones 2 hasta 4. Cuando llega a 5 break.
    print(f"\n\nPeak ranges values \n{peaks_range}")
    print(f"\n\nABS ranges values \n{abs_range}")
    
    return peaks_range,abs_range

In [35]:
def compute_mean(peaks_samples, abs_samples):
    avg_peaks = peaks_samples.mean()
    avg_abs = abs_samples.mean()
    return avg_peaks, avg_abs

In [38]:
def paste_avgs(df_results, row_in_df, temp_peak_avg,temp_abs_avg):

    df_results.iloc[row_in_df] = [temp_peak_avg,temp_abs_avg]
    print(df_results.head())

## User interaction: 
#### Specify the rows to be analyzed: [30]

### Review :  
#### Temporary averages -- [38]

## User interaction: 
#### Paste results in output data frame [41]

In [12]:
df_online.head(20)

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059
14     Run 15 - Magnum_380_run_6_5mph_1             0.081             0.021

## User interaction: 
#### Specify the rows to be analyzed: [30]

In [36]:
dataframe_to_analyze =  df_online

##///////////////////////////////////////////////////////////////

## Specify the index to start the analysis
initial_index = 8

## Specify the index number of samples collected
num_samples = 3

##///////////////////////////////////////////////////////////////

ranges_peak, ranges_abs = get_ranges(dataframe_to_analyze,initial_index,num_samples)

Rows from: 8 to 10
                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
8    Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9   Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10  Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023


Peak ranges values
8     0.109
9     0.098
10    0.065
Name: MAXABSIMPXTE (m), dtype: float64


ABS ranges values
8     0.037
9     0.030
10    0.023
Name: AVGABSIMPXTE (m), dtype: float64

# Review :  
#### Do averages make sense?

In [37]:
peak_avg,abs_avg = compute_mean(ranges_peak,ranges_abs)

print(f"\n\nPeak ranges values \n{ranges_peak}")
print(f"\nPeak average for the {num_samples} samples: {peak_avg}")

print(f"\n\nABS ranges values \n{ranges_abs}")
print(f"\nABS average for the {num_samples} samples: {abs_avg}")

Peak ranges values
8     0.109
9     0.098
10    0.065
Name: MAXABSIMPXTE (m), dtype: float64

Peak average for the 3 samples: 0.09066666666666667


ABS ranges values
8     0.037
9     0.030
10    0.023
Name: AVGABSIMPXTE (m), dtype: float64

ABS average for the 3 samples: 0.03

# User interaction: 
#### Select the row to paste the results

In [32]:
##///////////////////////////////////////////////////////////////

#Specify where you want to paste these results
row_to_paste = 2

##///////////////////////////////////////////////////////////////

paste_avgs(output_df,row_to_paste,peak_avg,abs_avg)

  PEAKS AVG   ABS AVG
0     0.036     0.019
1  0.046667     0.015
2  0.093667  0.026667
3       NaN       NaN
4       NaN       NaN