In [34]:
import pandas as pd
from openpyxl import load_workbook
from openpyxl.styles import PatternFill, Font

In [2]:
bundle_version = 'mod_sum_v3'

Definir los archivos CSV que se usaran para los escenarios online y curve

Para online: SettleAnalysis


Para curve: EngageAnalysis

In [3]:
#vehicle settle para Online runs 

#Engaged Analysis para Curve runs

online_csv_path = 'Vehicle Settled Results Metrics - VehicleSettledAnalysis.csv'
curve_csv_path  = 'Results Metrics - EngagedAnalysis.csv'

In [4]:
# Se especifica aqui, Software version y el nombre del archivo excel que se exportara

filename_excel_report = bundle_version + '_Test Status Report.xlsx' 


#Se leen los archivos que tienen la informacion para el analisis 


df_OnlineAnalysis_csv = pd.read_csv(online_csv_path)  
df_EngagedAnalysis_csv = pd.read_csv(curve_csv_path)



#Specs for peaks and absolutes
spec_peaks = .05 # Spec for peaks - 5 cm  
speak_abs = .025 # Spec for abs - 2.5 cm

In [5]:
# Lista con el nombre de las columnas que nos seran utiles para el analisis. 

# Estas columnas se usaran para crear el df_online y el df_curve
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)']

Se crea el dataframe que contendra las corridas para el df_online

In [6]:
# Se crea una lista donde se guardan los rows que devuelven true cuando se lee la palabra straight
online_runs = df_OnlineAnalysis_csv["Data Source"].str.contains('straight')


df_online = df_OnlineAnalysis_csv.loc[online_runs][perf_metrics]
df_online.index = range(1,len(df_online) + 1)
df_online.rename(columns={'Data Source': 'Run Description'},inplace=True)

Verifica que solo se vean las corridas straight en el df_online

In [7]:
df_online

,Run Description,MAXABSIMPXTE (m),AVGABSIMPXTE (m)
1,Run 1 - Magnum_380_straight_1.25mph_run1,0.047,0.028
2,Run 2 - Magnum_380_straight_1.25mph_run2,0.028,0.015
3,Run 3 - Magnum_380_straight_1.25mph_run3,0.031,0.009
4,Run 4 - Magnum_380_straight_3.1mph_run1,0.038,0.010
5,Run 5 - Magnum_380_straight_3.1mph_run2,0.027,0.016
6,Run 6 - Magnum_380_straight_3.1mph_run2,0.064,0.019
7,Run 7 - Magnum_380_straight_3.1mph_run3,0.054,0.018
8,Run 8 - Magnum_380_straight_3.1mph_run3,0.040,0.014
9,Run 9 - Magnum_380_straight_6.2mph_run1,0.065,0.024
10,Run 10 - Magnum_380_straight_6.2mph_run1,0.049,0.017
11,Run 11 - Magnum_380_straight_6.2mph_run2,0.060,0.019
12,Run 12 - Magnum_380_straight_6.2mph_run3,0.053,0.014
13,Run 13 - Magnum_380_straight_9.2mph_run1,0.050,0.018
14,Run 14 - Magnum_380_straight_9.2mph_run1,0.121,0.023
15,Run 15 - Magnum_380_straight_9.2mph_run2,0.078,0.024
16,Run 16 - Magnum_380_straight_9.2mph_run2,0.062,0.034
17,Run 17 - Magnum_380_straight_9.2mph_run2,0.077,0.031
18,Run 18 - Magnum_380_straight_9.2mph_run2,0.079,0.028
19,Run 19 - Magnum_380_straight_9.2mph_run3,0.064,0.026
20,Run 20 - Magnum_380_straight_12.4mph_run1,0.087,0.029
21,Run 21 - Magnum_380_straight_12.4mph_run1,0.061,0.030
22,Run 22 - Magnum_380_straight_12.4mph_run2,0.044,0.016
23,Run 23 - Magnum_380_straight_12.4mph_run3,0.060,0.018

Se crea el dataframe que tendra las corridas para el df_curve

In [8]:
# Se crea una lista donde se guardan los rows que devuelven true cuando se lee la palabra straight
curve_runs = df_EngagedAnalysis_csv["Data Source"].str.contains('curve')


df_curve = df_EngagedAnalysis_csv.loc[curve_runs][perf_metrics]
df_curve.index = range(1,len(df_curve) + 1)
df_curve.rename(columns={'Data Source': 'Run Description'},inplace=True)

Verifica que solo se vean las corridas curve en el df_curve

In [9]:
print(df_curve)

                           Run Description  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
1  Run 16 - Magnum_380_curve1deg_5mph_run1             0.071             0.020
2  Run 17 - Magnum_380_curve1deg_5mph_run2             0.061             0.019
3  Run 18 - Magnum_380_curve1deg_5mph_run3             0.056             0.019
4  Run 19 - Magnum_380_curve2deg_5mph_run1             0.094             0.027
5  Run 20 - Magnum_380_curve2deg_5mph_run2             0.109             0.022
6  Run 21 - Magnum_380_curve2deg_5mph_run3             0.110             0.023
7  Run 22 - Magnum_380_curve1deg_8mph_run1             0.165             0.072
8  Run 23 - Magnum_380_curve1deg_8mph_run2             0.153             0.062
9  Run 24 - Magnum_380_curve1deg_8mph_run3             0.152             0.067

Se crean los dataframes

df_perf_type : Contiene el tipo de online perfomance a evaluar, en este caso Straight

df_speeds_online : Contiene las velocidades de cada corrida

df_runs_number_online : Contine el numero de runs. Para online Straights seran 5.

df_peaks_avg_online : Contiene el average MAX por cada conjunto de muestras.

df_abs_avg_online: Contiene el average de XTE por cada conjunto de muestras

In [10]:
# Se crea el df que contendra los promedios de las corridas ONLINE unicamente para peaks o MAXABS

df_perf_type = pd.DataFrame(index= range(0,5), columns= ["Online Performance"]) 
df_speeds_online = pd.DataFrame(index= range(0,5), columns= ["Speed (mph)"]) 
df_runs_number_online = pd.DataFrame(index= range(0,5), columns= ["Run #"]) 
df_peaks_avg_online =  pd.DataFrame(index= range(0,5), columns= ["Average MAX XTE of runs (m)"]) 
df_abs_avg_online =  pd.DataFrame(index= range(0,5), columns= ["Average XTE of runs (m)"])

In [11]:
df_online

,Run Description,MAXABSIMPXTE (m),AVGABSIMPXTE (m)
1,Run 1 - Magnum_380_straight_1.25mph_run1,0.047,0.028
2,Run 2 - Magnum_380_straight_1.25mph_run2,0.028,0.015
3,Run 3 - Magnum_380_straight_1.25mph_run3,0.031,0.009
4,Run 4 - Magnum_380_straight_3.1mph_run1,0.038,0.010
5,Run 5 - Magnum_380_straight_3.1mph_run2,0.027,0.016
6,Run 6 - Magnum_380_straight_3.1mph_run2,0.064,0.019
7,Run 7 - Magnum_380_straight_3.1mph_run3,0.054,0.018
8,Run 8 - Magnum_380_straight_3.1mph_run3,0.040,0.014
9,Run 9 - Magnum_380_straight_6.2mph_run1,0.065,0.024
10,Run 10 - Magnum_380_straight_6.2mph_run1,0.049,0.017
11,Run 11 - Magnum_380_straight_6.2mph_run2,0.060,0.019
12,Run 12 - Magnum_380_straight_6.2mph_run3,0.053,0.014
13,Run 13 - Magnum_380_straight_9.2mph_run1,0.050,0.018
14,Run 14 - Magnum_380_straight_9.2mph_run1,0.121,0.023
15,Run 15 - Magnum_380_straight_9.2mph_run2,0.078,0.024
16,Run 16 - Magnum_380_straight_9.2mph_run2,0.062,0.034
17,Run 17 - Magnum_380_straight_9.2mph_run2,0.077,0.031
18,Run 18 - Magnum_380_straight_9.2mph_run2,0.079,0.028
19,Run 19 - Magnum_380_straight_9.2mph_run3,0.064,0.026
20,Run 20 - Magnum_380_straight_12.4mph_run1,0.087,0.029
21,Run 21 - Magnum_380_straight_12.4mph_run1,0.061,0.030
22,Run 22 - Magnum_380_straight_12.4mph_run2,0.044,0.016
23,Run 23 - Magnum_380_straight_12.4mph_run3,0.060,0.018

In [12]:
#scenarios : Es una lista que servira para separar las corridas en bloques. 
#            El nombre de los archivos deben contener este texto para separar.

scenarios = ["1.25mph", "3.1mph", "6.2mph", "9.2mph", "12.4mph"] 

#runs_online: Es una lista que servira para llenar el df_runs_number_online con los numeros del 1 al 5.
runs_online = range(1,6)


#avg_max es un diccionario, que llevara por key cada valor de esceanrio y por clave, el promedio
        # de las corridas para ese escenario.
avg_max = {
    s: round(
        df_online.loc[
            df_online["Run Description"].str.contains(s, na=False),
            "MAXABSIMPXTE (m)"
        ].mean(),
        2
    )
    for s in scenarios
}
avg_max = list(avg_max.values())


# Se hace el mismo proceso para avg_abs. 
avg_abs = {
    a: round(
        df_online.loc[
            df_online["Run Description"].str.contains(a, na=False),
            "AVGABSIMPXTE (m)"
        ].mean(),
        2
    )
    for a in scenarios
}


avg_abs_results = list(avg_abs.values())

In [13]:
avg_max

[np.float64(0.04),
 np.float64(0.04),
 np.float64(0.06),
 np.float64(0.08),
 np.float64(0.06)]

In [ ]:
#Aqui asignaremos en cada uno de los renglones la informacion que necesitamos para cada df.

for i in range(5):
    df_perf_type.loc[i,'Online Performance'] = 'Straight'
    df_speeds_online.loc[i,'Speed (mph)'] = scenarios[i]
    df_runs_number_online.loc[i,'Run #'] = runs_online[i]
    df_peaks_avg_online.loc[i,'Average MAX XTE of runs (m)'] = avg_max[i]
    df_abs_avg_online.loc[i, 'Average XTE of runs (m)'] = avg_abs_results[i]

In [ ]:
#Concatemos de manera horizonal cada uno de los dataframes para generar df_output_online

df_output_online = pd.concat([
                                df_perf_type,
                                df_speeds_online,
                                df_runs_number_online,
                                df_peaks_avg_online,
                                df_abs_avg_online], axis=1)

In [26]:
df_output_online

,Online Performance,Speed (mph),Run #,Average MAX XTE of runs (m),Average XTE of runs (m)
0,Straight,1.25mph,1,0.04,0.02
1,Straight,3.1mph,2,0.04,0.02
2,Straight,6.2mph,3,0.06,0.02
3,Straight,9.2mph,4,0.08,0.03
4,Straight,12.4mph,5,0.06,0.02

Realizamos ahora la tabla para los scenarios de curvas. 
Los dataframes utilizados tienen el mismo objetivo que los creados para straight runs, solo llevan como distintivo el _curve

In [17]:
# Se crea el df que contendra los promedios de las corridas Curve unicamente para peaks o MAXABS

df_perf_type = pd.DataFrame(index= range(0,3), columns= ["Online Performance"]) 
df_speeds_curvatures = pd.DataFrame(index= range(0,3), columns= ["Speed / Curvature"]) 
df_runs_number_curve = pd.DataFrame(index= range(0,3), columns= ["Run #"]) 
df_peaks_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average MAX XTE of runs (m)"]) 
df_abs_avg_curve =  pd.DataFrame(index= range(0,3), columns= ["Average XTE of runs (m)"])

In [ ]:
# scenarios: Es la lista que contendra las strings para separar las corridas en bloques y 
            #con eso calcular el promedio

scenarios = ["curve1deg_5mph", "curve2deg", "curve1deg_8mph"]

# speeds_curvatures: Esta lista solo contiene las velocidades y las curvas para 
#  llenar el df_speeds_curvatures

speeds_curvatures = ["5mph / 1 deg/m", "5 mph / 2deg/m", "8mph / 1 deg/m"]

# runs_curve: Es la lista que serivira para llenar el df_runs_number. Solo es la sucesion de 1 a 4.
runs_curve = range(1,4)

avg_max = {
    s: round(
        df_curve.loc[
            df_curve["Run Description"].str.contains(s, na=False),
            "MAXABSIMPXTE (m)"
        ].mean(),
        2
    )
    for s in scenarios
}
avg_max = list(avg_max.values())

avg_abs = {
    a: round(
        df_curve.loc[
            df_curve["Run Description"].str.contains(a, na=False),
            "AVGABSIMPXTE (m)"
        ].mean(),
        2
    )
    for a in scenarios
}


avg_abs_results = list(avg_abs.values())

In [ ]:
# Se colocan los resultados obtenidos en cada uno de los dataframes:
# Para df_perf_type solo se llenar cada row con el string Curve.
# Para df_speeds_curvatures se llena cada row con la lista speed_curvatures.
# Para df_runs_number_curve se llena cada row con una lista run_curve.


# Para df_peaks_avg_curve se llena cada row usando la lista avg_max que contiene 
# los promedios MAX por cada corrida.

# Para df_abs_avg_curve se llena cada row usando la lista abs_avg_curve que contiene
# los promedios ABS por cada corrida. 


for i in range(3):
    df_perf_type.loc[i,'Online Performance'] = 'Curve'
    df_speeds_curvatures.loc[i,'Speed / Curvature'] = speeds_curvatures[i]
    df_runs_number_curve.loc[i,'Run #'] = runs_curve[i]
    df_peaks_avg_curve.loc[i,'Average MAX XTE of runs (m)'] = avg_max[i]
    df_abs_avg_curve.loc[i, 'Average XTE of runs (m)'] = avg_abs_results[i]

In [30]:
df_output_curve = pd.concat([
                              df_perf_type,
                              df_speeds_curvatures,
                              df_runs_number_curve,
                              df_peaks_avg_curve,
                              df_abs_avg_curve], axis=1)

In [31]:
df_output_curve

,Online Performance,Speed / Curvature,Run #,Average MAX XTE of runs (m),Average XTE of runs (m)
0,Curve,5mph / 1 deg/m,1,0.06,0.02
1,Curve,5 mph / 2deg/m,2,0.1,0.02
2,Curve,8mph / 1 deg/m,3,0.16,0.07

In [32]:
# Se exportan los dataframes al mismo excel file. 
# Sheet name nos sirve para especificar el nombre que llevara la sheet donde se exportara el df


rows_spacing = 2

with pd.ExcelWriter(filename_excel_report) as writer:
   
    df_online.to_excel(writer, sheet_name= 'Online Runs',index=False)
    
    df_output_online.to_excel(writer, sheet_name= 'Online Runs',
                              startrow= len(df_online) + rows_spacing + 1,index=False)


    df_curve.to_excel(writer, sheet_name= 'Curve Runs',index=False)
    df_output_curve.to_excel(writer, sheet_name= 'Curve Runs',
                             startrow= len(df_curve) + rows_spacing + 1, index=False)

In [33]:
#Se abre el archivo usando openpyxl

#Aqui solo se crea la instancia para manipular el excel usando la libreria openpyxl
wb_file = load_workbook(filename_excel_report) 

#Seleccionamos la hoja que contine los resultados 
online_runs_sheet = wb_file['Online Runs']
curve_runs_sheet = wb_file['Curve Runs']


#Se crean los colores para cada celda
red_code = "FFC7CE"


# start color: Excel pinta la celda usando cierto patron, ya sea puntos o lineas,
# start color es en palabras resumidas el color de esos puntos con los que se llena la celda



red_fill = PatternFill(start_color = red_code,
                       fill_type = 'solid' )



#Se selecciona la hora con las corridas online - Online Runs SHEET

# Comenzamos desde el row 28, ya que no necesitamos leer el heading the la columna 

for idx_row in range(28,33):
        
        cell_peaks = online_runs_sheet.cell(row = idx_row, column = 4) # column 4 == es la columna D
        cell_abs = online_runs_sheet.cell(row = idx_row, column = 5) # column 4 == es la columna E

        if cell_peaks.value > spec_peaks:
            cell_peaks.fill = red_fill
        
        if cell_abs.value > speak_abs:
              cell_abs.fill = red_fill


#Se selecciona la hora con las corridas  - Curve Runs SHEET
for idx_row in range(14,17):
        
        cell_peaks = curve_runs_sheet.cell(row = idx_row, column = 4) # column 4 == es la columna D
        cell_abs = curve_runs_sheet.cell(row = idx_row, column = 5) # column 4 == es la columna E

        if cell_peaks.value > spec_peaks:
            cell_peaks.fill = red_fill
        
        if cell_abs.value > speak_abs:
              cell_abs.fill = red_fill



wb_file.save(filename_excel_report)