In [136]:
import pandas as pd

In [137]:
df = pd.read_csv('OnlineAnalysis.csv')

In [138]:
spec_peaks = .05 # Spec for peaks - 5 cm  
speak_abs = .025 # Spec for abs - 2.5 cm   
ONLINE_RUNS_COLLECTED = 14  # Normalmente aqui el valor aqui es 15.  RangeIndex: 14 entries, 0 to 13
                            # 5 runs x 3 samples = 15 ya que el cero se cuenta

In [139]:
#In case columns are not in CSV just raise an error

if 'MAXABSIMPXTE (m)' not in df.columns:
    raise KeyError(f"MAXABSIMPXTE (m) column is not in csv")

if 'AVGABSIMPXTE (m)' not in df.columns:
    raise KeyError(f"AVGABSIMPXTE (m) column is not in csv")

In [140]:
perf_metrics = ['Data Source','MAXABSIMPXTE (m)', 'AVGABSIMPXTE (m)'] # lista que solo tiene el nombre de las columnas que me interesa



df_online = df[perf_metrics].iloc[0:ONLINE_RUNS_COLLECTED] #Crea un df. Toma las columnas de la lista perf_metrics...
                                        #y los primeros 15 renglones. Estos renglones tienen la informacion de las corridas online

print(df_online.info())                                        #despues de ellas comienzan las curvas, y aquisitions. 
print(f'\n')
df_online.head(15)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Data Source       14 non-null     object
 1   MAXABSIMPXTE (m)  14 non-null     float64
 2   AVGABSIMPXTE (m)  14 non-null     float64
dtypes: float64(2), object(1)
memory usage: 468.0+ bytes
None

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0    Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1    Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017
2       Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3       Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4       Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012
5     Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6     Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7     Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023
8     Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9    Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10   Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059

#### Specify the ranges to analyze

In [141]:
run_1_start_index = 0
run_1_stop_index = 1

run_2_start_index = 2
run_2_stop_index = 4

run_3_start_index = 5
run_3_stop_index = 7

run_4_start_index = 8
run_4_stop_index = 10

run_5_start_index = 11
run_5_stop_index = 13

In [142]:
#Aqui solo se crean SUB-DATAFRAMES tomando como referencia el numero de fila de cuando empieza y cuando termina cada run en DATAFRAME_ONLINE.

run_1_ranges = df_online.iloc[run_1_start_index : run_1_stop_index+1]
run_2_ranges = df_online.iloc[run_2_start_index : run_2_stop_index+1]
run_3_ranges = df_online.iloc[run_3_start_index : run_3_stop_index+1]
run_4_ranges = df_online.iloc[run_4_start_index : run_4_stop_index+1]
run_5_ranges = df_online.iloc[run_5_start_index : run_5_stop_index+1]

In [143]:
#Verifica que los rangos sean correctos, visualmente
print(f"\t\t\tRUN 1 RANGE\n")
print(run_1_ranges)
print(f"\n\t\t\tRUN 2 RANGE\n")
print(run_2_ranges)
print(f"\n\t\t\tRUN 3 RANGE\n")
print(run_3_ranges)
print(f"\n\t\t\tRUN 4 RANGE\n")
print(run_4_ranges)
print(f"\n\t\t\tRUN 5 RANGE\n")
print(run_5_ranges)

			RUN 1 RANGE

                          Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
0  Run 1 - Magnum_380_run_1_1.25mph_2             0.036             0.021
1  Run 2 - Magnum_380_run_1_1.25mph_3             0.036             0.017

			RUN 2 RANGE

                       Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
2  Run 3 - Magnum_380_run_2_3mph_1             0.049             0.019
3  Run 4 - Magnum_380_run_2_3mph_2             0.041             0.014
4  Run 5 - Magnum_380_run_2_3mph_3             0.050             0.012

			RUN 3 RANGE

                         Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
5  Run 6 - Magnum_380_run_3_6.2mph_1             0.128             0.034
6  Run 7 - Magnum_380_run_3_6.2mph_2             0.089             0.023
7  Run 8 - Magnum_380_run_3_6.2mph_3             0.064             0.023

			RUN 4 RANGE

                           Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
8    Run 9 - Magnum_380_run_4_9.2mph_1             0.109             0.037
9   Run 10 - Magnum_380_run_4_9.2mph_2             0.098             0.030
10  Run 11 - Magnum_380_run_4_9.2mph_3             0.065             0.023

			RUN 5 RANGE

                            Data Source  MAXABSIMPXTE (m)  AVGABSIMPXTE (m)
11  Run 12 - Magnum_380_run_5_12.4mph_1             0.085             0.028
12  Run 13 - Magnum_380_run_5_12.4mph_2             0.141             0.045
13  Run 14 - Magnum_380_run_5_12.4mph_3             0.195             0.059

In [144]:
def compute_mean(range_run):
    avg_peaks = range_run['MAXABSIMPXTE (m)'].mean()
    avg_abs = range_run['AVGABSIMPXTE (m)'].mean()
    return avg_peaks, avg_abs

In [145]:
#Se crea una minifuncion que toma como entrada el SUB-DATAFRAME de cada run (run_x_ranges).
#Entrega una tupla que contine dos valores. El promedio de las columna MAXABSIMPXTE (m) y AVGABSIMPXTE (m)
#Esto se hace para para SUB-DATAFRAME


avg_run_1 = compute_mean(run_1_ranges)
avg_run_2 = compute_mean(run_2_ranges)
avg_run_3 = compute_mean(run_3_ranges)
avg_run_4 = compute_mean(run_4_ranges)
avg_run_5 = compute_mean(run_5_ranges)

In [146]:
columns_names = ["PEAKS AVG (m)", "ABS AVG (m)"] #se crea una lista con el nombre de las columnas que llevara el df de salida
output_df =  pd.DataFrame(index= range(5), columns=columns_names) #se crea el df de salida. 
                                                                # Contendra 5 renglones con los resultados de cada run.

In [147]:
#Asigna en cada renglon del dataframe de salida la tupla , que contiene los promedios AXABSIMPXTE (m) y AVGABSIMPXTE (m) por corrida 
output_df.iloc[0] = avg_run_1
output_df.iloc[1] = avg_run_2
output_df.iloc[2] = avg_run_3
output_df.iloc[3] = avg_run_4
output_df.iloc[4] = avg_run_5

In [148]:
#Crea una lista de 1 a 6. RangeIndex: 5 entries, 0 to 5.
#Esta sera la columna que tendra de encavezado RUNS #
runs = [f"run {i}" for i in range(1, 6)]
runs = pd.Series(runs)



#Crea una lista en donde sea FAIL si el promedio encontrado en PEAK AVG (m) para esa corrida es MAYOR al spec_PEAKS = .05 m
peak_results = ["Fail" if peak_run > spec_peaks else "Pass" for peak_run in output_df["PEAKS AVG (m)"]]
peak_results = pd.Series(peak_results)



#Crea una lista en donde sea FAIL si el promedio encontrado en ABS AVG (m) para esa corrida es MAYOR al spec_ABS = .025 m
abs_results = ["Fail" if peak_run > speak_abs else "Pass" for peak_run in output_df["ABS AVG (m)"]]
abs_results = pd.Series(abs_results)

In [149]:
#Crea una columna llamada 'RUN' en el df output_df y asignale la (PANDAS SERIES)lista 'runs'
output_df['RUN #'] = runs

#Crea una columna llamada 'STATUS - PEAKS AVG' en el df output_df y asignale la (PANDAS SERIES)lista 'peak_results'
output_df['STATUS - PEAKS AVG'] = peak_results

#Crea una columna llamada 'STATUS ABS AVG' en el df output_df y asignale la (PANDAS SERIES)lista 'abs_results'
output_df['STATUS ABS AVG'] = abs_results

#Reordena las columnas en este orden 'RUN','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG'
output_df = output_df[['RUN #','PEAKS AVG (m)','STATUS - PEAKS AVG','ABS AVG (m)','STATUS ABS AVG']]

In [150]:
output_df

   RUN # PEAKS AVG (m) STATUS - PEAKS AVG ABS AVG (m) STATUS ABS AVG
0  run 1         0.036               Pass       0.019           Pass
1  run 2      0.046667               Pass       0.015           Pass
2  run 3      0.093667               Fail    0.026667           Fail
3  run 4      0.090667               Fail        0.03           Fail
4  run 5      0.140333               Fail       0.044           Fail

In [151]:
df_online.iloc[0:run_5_stop_index+1].to_csv('Online_Summary.csv', index=False)

with open('Online_Summary.csv', 'a') as output_csv_f:
    output_csv_f.write('\n')
    output_csv_f.write(f'Acceptance criteria for PEAKS AVG {spec_peaks}m \n')
    output_csv_f.write(f'Acceptance criteria for ABS AVG {speak_abs}')
    output_csv_f.write('\n')
    output_csv_f.write('\n')


output_df.to_csv('Online_Summary.csv', mode='a', index=False)